# Generated by Django 4.1.7 on 2023-10-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
