# Generated by Django 4.1.7 on 2023-11-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
