# Generated by Django 4.1.7 on 2023-11-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'title', 'ordering': ['-pub_date'], 'verbose_name': 'posts'},
        ),
    ]
