# Generated by Django 4.1.7 on 2023-11-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'tag'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='tag',
        ),
    ]
